# Generated by Django 6.1 on 2026-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('marital_status', models.CharField(max_length=50)),
                ('children', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skills', models.TextField()),
                ('work_time', models.CharField(max_length=100)),
                ('food_pref', models.CharField(max_length=50)),
                ('work_pref', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('approved', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='helpers/photos/')),
                ('latest_photo', models.ImageField(blank=True, null=True, upload_to='helpers/latest_photos/')),
                ('aadhaar_front', models.ImageField(blank=True, null=True, upload_to='helpers/aadhaar/')),
                ('aadhaar_back', models.ImageField(blank=True, null=True, upload_to='helpers/aadhaar/')),
            ],
        ),
    ]
