# Generated by Django 6.1 on 2026-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
