# Generated by Django 6.1 on 2026-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_helper_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='helper',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='helper',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helper',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
